config/routes.rb
Rails.application.routes.draw do
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in', as: :guest_customer_session
    get 'customers', to: 'public/registrations#new'
  end

  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admin/sessions#guest_sign_in', as: :guest_admin_session
  end

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    resources :customers, only: [:index] do
      member do
        patch :retire
        patch :revive
      end
      resources :posts, only: [:index, :show, :destroy] do
        resources :post_comments, only: [:index, :destroy]
      end
    end

    resources :genres, only: [:index, :destroy]

    resources :tackles, only: [:index, :show, :destroy]

    resources :post_comments, only: [:index, :destroy]
  end

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: 'public/registrations',
  sessions: 'public/sessions'
  }

  scope module: :public do
    root to: 'homes#top'
    get 'about', to: 'homes#about'

    get "customers/confirm" => "customers#confirm"
    patch "customers/withdraw" => "customers#withdraw"

    resources :customers, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :posts, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :edit, :destroy, :update]
      resource :favorites, only: [:create, :destroy]
      member do
       patch 'tackle_selection', to: 'posts#tackle_selection'
      end
    end

    resources :favorites, only: [:index]

    resources :notifications, only: [:index]

    resources :genres, only: [:index, :create, :edit, :update, :destroy] do
      get 'posts', to: 'posts#genre', as: 'posts', on: :member
    end

    resources :tackles, only: [:new, :create, :index, :show, :edit, :update, :destroy]
      get '/searches', to: 'searches#search'
      get 'tides/graf', to: 'tides#graf'
      get 'tides/get_port_name', to: 'tides#get_port_name'
    resources :tides, only: [:index]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  GUEST_CUSTOMER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_CUSTOMER_EMAIL) do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "ゲスト"
    end
  end

  def guest_customer?
    email == GUEST_CUSTOMER_EMAIL
  end

  has_many :posts
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :genres
  has_one_attached :image

  # フォロー
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  # フォロワー
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # タックル
  has_many :tackles

  # 通知
  has_many :notifications, dependent: :destroy

  def get_image
  if image.attached?
    image
  else
    '/assets/no_image.jpg'
  end
  end

  def follow(other_customer)
    relationships.create(followed_id: other_customer.id) unless self == other_customer
  end

  def unfollow(other_customer)
  relationships.find_by(followed_id: other_customer.id).destroy if following?(other_customer)
  end

  def following?(other_customer)
  followings.include?(other_customer)
  end

end



# ２５行目「has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy」の「class_name: "Relationship",」について
# これは、関連するモデルがRelationshipであると、「明示的」にモデルのクラス名を指定している。
# なぜ明示的に指定するのか。
# -「Customer」モデルが「Relationship」モデルと2種類の異なる関係を持っているから。
# -2種類の異なる関係とは、フォロー「Followings」とフォロワー「Followers」のこと。この２つは、内部的に「Relationship」モデルで表されている。
# -Railsには、この「Followings」と「Followers」の関連から、「Relationship」モデルを直接推測することができないので、明示的に「Relationship」モデルを指定する。

# 要するに、明示していない場合、「Relationship」モデルを介して、フォローしているCustomerの集まりを表現している「has_many :followings」を、Railsは「Followings」モデルだと判断して、
# 存在しないモデルを探してしまう。そこで、「class_name」オプションを使って、Railsに正確なモデルを指定する必要がある。

# ２９行目のフォローワー関係を記述する際も、reverse_of_relationshipsとfollowersという存在しないモデルを探さないように明示的に「Relationship」モデルを指定している。

# ここでの、「has_many :relationships」と「has_many :reverse_of_relationships」は「Relationship」モデルを中間テーブルとして使用していて、
# 「follower_id」を外部キーとして持っている。「follower_id」は、フォローしている、又は、フォローされているCustomer（自分自身）のIDのこと。

# 「Relationship」モデルは中間テーブルとして、２つの「follower_id」の外部キーを持って、どのCustomerがどのCustomerをフォローしているかを記録し、多対多の関係が実現している。

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_customer, only: [:retire, :revive]

  def index
    @customers = Customer.all.page(params[:page]).per(20)
  end
  
  def retire
  @customer.update(is_deleted: true)
  redirect_to admin_customers_path, notice: '会員を退会させました'
  end

  def revive
    @customer.update(is_deleted: false)
    redirect_to admin_customers_path, notice: '会員を復活させました'
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12">

    <!-- 管理者専用アラート -->
    <% if admin_signed_in? %>
      <div class="alert alert-warning" role="alert">
        <strong>注意：</strong> こちらは管理者専用画面です
      </div>
    <% end %>
    <h1 class="mb-4 text-center">会員一覧</h1>
    <table class="table table-striped table-bordered">
      <colgroup>
        <col style="width: 20%;">
        <col style="width: 40%;">
        <col style="width: 20%;">
        <col style="width: 20%;">
      </colgroup>
    <thead class="thead-dark">
      <tr>
        <th scope="col" class="text-center">名前</th>
        <th scope="col" class="text-center">メールアドレス</th>
        <th scope="col" class="text-center">退会／復活</th>
        <th scope="col" class="text-center">現在のステータス</th>
      </tr>
    </thead>
    <tbody>
      <% if @customers.any? %>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= link_to customer.name, admin_customer_posts_path(customer_id: customer.id) %></td>
          <td class="break-word"><%= customer.email %></td>
          
          <td class="text-center">
            <% if customer.is_deleted %>
            <%= link_to '入会する', revive_admin_customer_path(customer), method: :patch, class: 'btn btn-success btn-sm' %>
            <% else %>
            <%= link_to '退会する', retire_admin_customer_path(customer), method: :patch, data: { confirm: '本当に退会させますか？' }, class: 'btn btn-danger btn-sm' %>
            <% end %>
          </td>

          <td class="text-center">
            <% if customer.is_deleted %>
            <i class="fas fa-times-circle text-danger"></i> 退会済み
            <% else %>
            <i class="fas fa-check-circle text-success"></i> 入会済み
            <% end %>
          </td>
        </tr>
        <% end %>
        <% else %>
        <p class="text-center">会員情報がありません</p>
      <% end %>
    </tbody>
    </table>
    </div>
  </div>
  <%= paginate @customers %>
</div>