config/routes.rb
Rails.application.routes.draw do
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in', as: :guest_customer_session
    get 'customers', to: 'public/registrations#new'
  end

  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admin/sessions#guest_sign_in', as: :guest_admin_session
  end

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    resources :customers, only: [:index] do
      member do
        patch :retire
        patch :revive
      end
      resources :posts, only: [:index, :show, :destroy] do
        resources :post_comments, only: [:index, :destroy]
      end
    end

    resources :genres, only: [:index, :destroy]

    resources :tackles, only: [:index, :show, :destroy]

    resources :post_comments, only: [:index, :destroy]
  end

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: 'public/registrations',
  sessions: 'public/sessions'
  }

  scope module: :public do
    root to: 'homes#top'
    get 'about', to: 'homes#about'

    get "customers/confirm" => "customers#confirm"
    patch "customers/withdraw" => "customers#withdraw"

    resources :customers, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :posts, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :edit, :destroy, :update]
      resource :favorites, only: [:create, :destroy]
      member do
       patch 'tackle_selection', to: 'posts#tackle_selection'
      end
    end

    resources :favorites, only: [:index]

    resources :notifications, only: [:index]

    resources :genres, only: [:index, :create, :edit, :update, :destroy] do
      get 'posts', to: 'posts#genre', as: 'posts', on: :member
    end

    resources :tackles, only: [:new, :create, :index, :show, :edit, :update, :destroy]
      get '/searches', to: 'searches#search'
      get 'tides/graf', to: 'tides#graf'
      get 'tides/get_port_name', to: 'tides#get_port_name'
    resources :tides, only: [:index]
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  belongs_to :customer
  validates :name, uniqueness: { scope: :customer_id, case_sensitive: false },
                    presence: true,
                    length: { maximum: 50 }

  before_save :downcase_name

  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end

  private

  def downcase_name
    self.name = name.strip.downcase
  end
end

# 勉強メモ
# ジャンル名が英字の場合
# before_saveは、データベースに保存する前に実行されるコールバックで、downcase_nameはメソッド名。
# downcase_nameメソッドは、name属性を小文字に変換し、文字列の前後にある空白を削除する。
# 「strip」で文字列の前後の空白を切り取り、「downcase」で大文字を小文字に変換する。
# 「self」とは、現在のオブジェクト自身（操作しているモデルのインスタンスのname属性）を指す。
# privateをこのオブジェクトが保持しているデータとメソッドを外部から隠蔽するもの ＝ カプセル化
# 属性から値を読み出す場合、selfは省略可能。しかし、Rubyでは属性への値の代入には原則としてselfを使用する。



# 属性とカラムの違い
# ざっくり説明すると、DB設計の段階ではnameは「カラム」で、そこからオブジェクト指向を用いた実際の開発段階に進むとカラムではなく「属性」と呼ぶ
# 属性とは、オブジェクト指向プログラミングにおいて、クラス（設計書）のインスタンス（実際の物）が持つ特性や状態を示すデータのこと。
# Rubyでは、ActiveRecordのようなORM（Object-Relational Mapping）を利用することで、データベースのカラムをクラスの属性として扱う。
# ORMを使用することで、データベースのカラムとオブジェクトの属性間で自動的にマッピングが行われる。すなわち、オブジェクト指向プログラミングでDBを操作できる。



# Ransack4の検索機能の導入が煩雑に感じるのは、セキュリティのため。
# ①「ransackable_attributes」メソッドで、検索可能な属性を制限している。　＝　属性を指定
# ②「ransackable_associations」メソッドで、どの関連付けを検索に使用できるか指定している。　＝　関連（例えば、他のモデルへのbelongs_to、has_many、has_oneなどの関連）を指定

# GenreモデルがCustomerモデルに従属(belongs_to)しているから「ransackable_attributes」メゾットを使うわけではないことに注意する。
# ransackable_attributesメソッドの使用は、モデルが他のモデルに従属しているかどうかとは関係なく、どの属性をユーザーに公開して検索可能にするか

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.order(created_at: :desc).page(params[:page]).per(12)
  end

  def destroy
    @genre = Genre.find(params[:id])
    if @genre.destroy
      redirect_to admin_genres_path, notice: '魚種が削除されました'
    else
      redirect_to admin_genres_path, alert: '魚種の削除に失敗しました'
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/admin/genres/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12">
      <!-- 管理者専用アラート -->
      <% if admin_signed_in? %>
        <div class="alert alert-warning" role="alert">
          <strong>注意：</strong> こちらは管理者専用画面です
        </div>
      <% end %>
      <h1 class="mb-4 text-center">魚種一覧</h1>
      <table class="table table-striped table-bordered">
         <colgroup>
          <col style="width: 40%;">
          <col style="width: 40%;">
          <col style="width: 20%;">
         </colgroup>
        <thead class="thead-dark">
          <tr>
            <th scope="col" class="text-center">登録者</th>
            <th scope="col" class="text-center">魚種名</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% if @genres.any? %>
            <% @genres.each do |genre| %>
              <tr>
                <td class="break-word"><%= link_to genre.customer.name, admin_customer_posts_path(customer_id: genre.customer.id) %></td>
                <td class="break-word"><%= genre.name %></td>
                <td class="text-center">
                  <%= link_to '管理者権限で削除', admin_genre_path(genre), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger btn-sm' %>
                </td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td colspan="3" class="text-center">魚種が登録されていません</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= paginate @genres %>
</div>