config/routes.rb
Rails.application.routes.draw do
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in', as: :guest_customer_session
    get 'customers', to: 'public/registrations#new'
  end

  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admin/sessions#guest_sign_in', as: :guest_admin_session
  end

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    resources :customers, only: [:index] do
      member do
        patch :retire
        patch :revive
      end
      resources :posts, only: [:index, :show, :destroy] do
        resources :post_comments, only: [:index, :destroy]
      end
    end

    resources :genres, only: [:index, :destroy]

    resources :tackles, only: [:index, :show, :destroy]

    resources :post_comments, only: [:index, :destroy]
  end

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: 'public/registrations',
  sessions: 'public/sessions'
  }

  scope module: :public do
    root to: 'homes#top'
    get 'about', to: 'homes#about'

    get "customers/confirm" => "customers#confirm"
    patch "customers/withdraw" => "customers#withdraw"

    resources :customers, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :posts, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :edit, :destroy, :update]
      resource :favorites, only: [:create, :destroy]
      member do
       patch 'tackle_selection', to: 'posts#tackle_selection'
      end
    end

    resources :favorites, only: [:index]

    resources :notifications, only: [:index]

    resources :genres, only: [:index, :create, :edit, :update, :destroy] do
      get 'posts', to: 'posts#genre', as: 'posts', on: :member
    end

    resources :tackles, only: [:new, :create, :index, :show, :edit, :update, :destroy]
      get '/searches', to: 'searches#search'
      get 'tides/graf', to: 'tides#graf'
      get 'tides/get_port_name', to: 'tides#get_port_name'
    resources :tides, only: [:index]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  # 会員
  belongs_to :customer
  # タックル
  belongs_to :tackle, optional: true
  # コメント
  has_many :post_comments, dependent: :destroy
  # いいね
  has_many :favorites, dependent: :destroy
  # 通知
  has_many :notifications, as: :notifiable, dependent: :destroy
  # 釣り方
  has_many :rig_posts, dependent: :destroy
  has_many :rigs, through: :rig_posts
  attr_accessor :rig_list

  validate :validate_genre_presence
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 500 }
  validates :location, presence: true


  # 投稿のバリデーション
  def validate_genre_presence
    # 既存の魚種が選択されていない、かつ、新規の魚種が空欄の場合
    if genre_name.blank? && new_genre_name.blank?
      errors.add(:base, '既存の魚種を選択するか、新規の魚種名を入力してください')
    end

    # 新規の魚種は、その名前でジャンルが存在するかチェックし、存在しなければ新規ジャンルで作成
    unless new_genre_name.blank?
      new_genre = Genre.find_or_create_by(name: new_genre_name)
      # 新規の魚種をPostに関連付け
      self.genre_name = new_genre.name 
    end
  end
  
  # 新規の魚種
  attr_accessor :new_genre_name

  # いいね
  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end

  # 画像
  has_one_attached :image

  # no_image画像 
  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end

  # 釣り方
  def save_rigs(rigs)
    rig_list = rigs.split(/[[:blank:]]+/)
    current_rigs = self.rigs.pluck(:name)

    old_rigs = current_rigs - rig_list
    new_rigs = rig_list - current_rigs
    old_rigs.each do |old|
      self.rigs.delete Rig.find_by(name: old)
  end

    new_rigs.each do |new|
      new_post_rig = Rig.find_or_create_by(name: new)
      self.rigs << new_post_rig
    end
  end

  after_find :rigs_to_rig_list
  def rigs_to_rig_list
    if self.rigs && self.rigs.any?
      self.rig_list = self.rigs.map{|o| o.name }.join(" ")
    end
  end
  
  before_update :update_rigs
  def update_rigs
    save_rigs(self.rig_list)
  end

  after_create do
    customer.followers.each do |follower|
      notifications.create(customer_id: follower.id)
    end
  end  

  # 検索機能
  def self.ransackable_attributes(auth_object = nil)
    ["body", "genre_name"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["post_comments", "rig_posts", "rigs", "tackle"]
  end
end


#勉強メモ
# ５行目の「optional:ture」は、投稿時にタックルの記載が必須ではないことを意味する


# １１行目の「as: :notifiable」は、ポリモーフィック関連。
# -ポリモーフィック関連とは、あるモデルが複数の異なるモデルと関連付けされるような関係（多様性）。
# -Railsでは、asオプションを使ってポリモーフィック関連を実装する。

# -ポリモーフィック関連によって、「Notification」モデルは、「Post」モデルだけではなく、通知が可能な他の任意のモデル（ex: 「Comment」モデルや「Favorite」モデルなど）とも関連付けることができる。
# -「Notification」モデルと通知されるモデル（「Post」モデル）は１：多の関係になり、通知対象が削除された場合は通知自体が削除される。＝１つの通知は１つの投稿に関連づけられるが、投稿は複数の通知を持つことができる。
# -１つの通知は１つの投稿に関連づけられるが、投稿は複数の通知を持つことができる。

# -上記をコードにすると、
# --「Notification」モデル　：　belongs_to :notifiable, polymorphic: true
# --「Post」モデル　：　has_many :notifications, as: :notifiable, dependent: :destroy

# 補足として、ポリモーフィック関連はデータモデルの設計に柔軟であるが、クエリが複雑になり、アプリのパフォーマンスに影響するので注意する。



# Postモデル内のransack検索機能のカスタマイズ
# 「ransackable_attributes」メソッド: 検索に使用可能なPostモデルの属性を制限する。ここでは「body」と「genre_name」のみを検索対象として指定。
# -これにより、Postの内容（body）や魚種（genre_name）に基づいて検索を行うことが可能になる。

# 「ransackable_associations」メソッド: Postモデルが関連付けることができる他のモデルを検索に含める設定。「post_comments」, 「rig_posts」, 「rigs」, 「tackle」を検索に含めることが指定されている。
# -この設定により、Postに関連付けられたコメント（post_comments）、リグ（rigs）、タックル（tackle）などを通じた検索が可能になる。
# -「Post」モデルが他のモデルと関連付けされているからこそ、このメソッドが重要。このメソッドが指定されていない場合、Ransackで特定のモデルに関連付けられている他のモデルを検索対象にできない。

# Ransack4を用いた検索設定は、アプリケーションの検索機能を強化し、ユーザーが望む情報をより効率的に見つけられるようにするためのもの。
# -特に、検索可能な属性や関連を明示的に指定することで、セキュリティの強化に寄与し、不正な検索クエリによるデータ漏洩リスクを低減する。



# 17行目の「validate :validate_genre_presence」はカスタムバリデーションメソッド。投稿時に新規または既存の魚種を必ず選択しなければならない。
# -24行目の「validate_genre_presence」メソッドで行っている処理は２つ。
# --①既存と新規の魚種のチェック
# ---「genre_name.blank?」かつ「new_genre_name.blank?」の場合に、エラーメッセージを表示すること。

# --②新規の魚種の処理
# ---新規の魚種のフォームが空ではない（unless）場合に、「Genre.find_or_create_by(name: new_genre_name)」で入力された魚種が「Genre」モデルに存在するか確認して、存在しなければ新規の魚種として追加する。

# 補足として、Railsの「find_or_create_by」メソッドについて
# -指定された条件に一致するレコードをデータベースから検索し、一致するレコードが「存在する場合」は、そのオブジェクトを返す。一方で、「存在しない場合」は、新しいレコードを作成して保存し、その新しいオブジェクトを返す。
# --「new_genre = Genre.find_or_create_by(name: new_genre_name)」では、「name」が「new_genre_name」に一致するGenreオブジェクトをデータベースから探す。
# --例：新規の魚種に「マグロ」と入力されていたら、「マグロ」というGenreオブジェクトをデータベースに存在していないか探す。
# --もし「マグロ」が存在していれば、マグロを左辺の「new_genre」に代入する。存在しなければ、「name」属性が「マグロ」という新しい魚種をデータベースに保存後、「new_genre」に代入する。

# Railsの「find_or_create_by」メソッドの利点
# -①効率的：存在の確認と作成の処理を１行で記述できる。
# -②DRYの原則：「検索するたびに存在の確認して作成する」というような処理を繰り返し書くことを避けることができる。
# -③一貫性：新しいレコード（PFでいう新規の魚種）が必要な場合に、モデルのバリデーションを利用して、一貫した処理を行うことで、データの整合性を保つことができる。



# 39行目の「attr_accessor :new_genre_name」はRubyのメソッドであり、仮想属性を定義するために使用される。＝アトリビュート・アクセサー
# -「仮想属性」は、ゲッター（読み取りメソッド）とセッター（書き込みメソッド）を自動的に定義し、インスタンス変数に対して読み書きを可能にする。

# ゲッターとセッターとは、オブジェクト指向プログラミングにおいて、オブジェクトのプロパティ（属性）へのアクセス方法を提供するメソッド

# -「ゲッターとセッターが自動定義される」ことにより、以下のような操作が可能になる。
# --post = Post.new     ：Postオブジェクトを作成
# --post.new_genre_name = "Fish"  ：セッターメソッドを使ってnew_genre_name属性に値（Fish）を設定
# --puts post.new_genre_name      ：ゲッターメソッドを使ってnew_genre_name属性の値を取得して表示

# -「attr_accessor :new_genre_name」を使用して、Postモデルに仮想属性new_genre_nameを定義することで、新規に提案された魚種名を一時的に保持できる。
# -この仮想属性は、ユーザーからの入力を受け取り、その後の処理（例えば、Genreモデルへの新規魚種の保存）に利用される。しかし、このデータはPostモデルのデータベーステーブルには保存されない。
# -一方で、Genreモデルに新規魚種を保存する場合は、直接name属性に魚種名を設定し、モデルをデータベースに保存する。この場合、attr_accessorを使用する必要はない。
# したがって、フォームから受け取ったデータをモデルの属性として一時的に扱いたいが、そのデータをデータベースに保存する必要がない場合に便利。

# 注意点
# new_genre = Genre.find_or_create_by(name: new_genre_name)における(name: new_genre_name)とattr_accessor :new_genre_nameにおけるnew_genre_nameは、同じnew_genre_nameを参照しているが、使い方に違いがある。
# -attr_accessor :new_genre_nameで定義されたnew_genre_name仮想属性は、ユーザーからの入力を一時的にモデル内で保持するために使用され、
# -new_genre = Genre.find_or_create_by(name: new_genre_name)の行でその値が使用されて、新規のジャンルがデータベースに存在するかどうかをチェック（または新しいものを作成）するという流れになる。
# つまり、前者のnew_genre_nameは仮想属性として、投稿フォームにユーザーが入力した新規の魚種を一時的に保持するためにPostモデルで使用され、後者のnew_genre_nameはGenreモデルのデータベース内で同じ魚種が存在するか確認して、存在しない場合には新しい魚種として保存する。



# 43行目「favorites.where(customer_id: customer.id).exists?」
# -このコードは、特定のCustomerが特定のPostに対して「いいね（Favorite）」を行っているかどうかを確認するために使用する。
# -「Favorite」モデルのデータベースを「where」メソッドで検索し、「customer_id」が現在のCustomerのIDと一致する「いいね」の存在を確認する。「exists?」メソッドを使って、検索条件に合致するレコードがデータベースに１つでも存在するかを調べる。
# --もし「exists?」メソッドがtrueを返せば、そのCustomerは既にそのPostに「いいね」をしているということになる。

# 注意点
# -いいねの存在を確認するのは「Post」モデルではなく、「Favorite」モデル。この「Favorite」モデルは、CustomerとPostの間の「いいね」関係を管理するための中間テーブルとして機能している。
# -「customer_id: customer.id」というハッシュ構文は、検索条件として「customer_id」カラムの値が「customer.id」と一致するレコードを指定しています。
# これにより、指定された条件（customer_id: customer.idは、customer_idがcustomer.idに等しい）に基づいて「Favorite」モデルのデータベースから関連するレコードの存在を確認することが可能になります。



# 15行目「attr_accessor :rig_list」＝仮想属性
# -「Post」モデルのデータベースには保存されず、フォームから送信された釣り方のリストを一時的に保持するために使われる。

# 59行目「save_rigs(rigs)」メソッド
# -rig_list に格納されたデータ（フォームから送信されたリグのリスト）を処理し、新しいリグを Rig モデルのデータベースに追加したり、更新したり、不要になったRigを削除したりする。
# -「rigs.split(/[[:blank:]]+/)」で、Rigsを空白文字で区切る。

# 61行目「self.rigs.pluck(:name)」で、「current_rigs」（現在投稿に紐つけられているリグのリスト）を取得する。＝投稿に対してリグの更新機能（63〜65行目）を正確に行うために必要。
# -「old_rigs = current_rigs - rig_list」で、既存のリグから削除するリグを特定する。
# -「new_rigs = rig_list - current_rigs」で、新たに追加するリグを特定する。
# -「old_rigs.each」で、削除するリグを１つずつ取り出して、
# -「self.rigs.delete Rig.find_by(name: old)」によって、それぞれのリグを投稿から削除する。

# 69行目「new_rigs.each do |new|」で、Customerが新しく追加したリグのリスト（new_rigs）から１つずつリグ（new）を取り出す。
# -「Rig.find_or_create_by(name: new) 」で、new（新しいリグの名前）に一致するリグが「Rig」モデルに存在するか確認して、存在しない場合は新しいリグとして、データベースに保存する。
# -「self.rigs << new_post_rig」で、Findされたリグ（または新しく作成されたリグ）を現在の投稿（Postモデルでselfが指すのはPostオブジェクト）に関連付けたリグのリストに追加する。

# selfの使用
# -RubyやRailsでは、特にモデル内で属性への代入を行う際にselfキーワードの使用が推奨されている。複数のオブジェクト間でデータが受け渡される場合、selfを使用することで、そのメソッド内で操作しているのがインスタンス自身の属性やメソッドであることを明示できる。
# -例えば、attr_accessorで定義された仮想属性や、データベースのカラムに直接対応する属性に値を設定する際には、self.attribute_name = valueの形式で記述すると、ローカル変数への代入とインスタンスの属性への代入を区別でき、コードの意図が明確になる。
# -selfの省略は、読み手がコードの意図を誤解する原因となったり、意図しない不具合を引き起こす可能性（特に属性への代入では使用を推奨）がある。コードの可読性とメンテナンス性を高めるために重要。

# 75行目「after_find :rigs_to_rig_list」
# -このコールバックは、Postオブジェクトがデータベースから取得された後に自動的に実行される。
# -実行時、self.rigsに関連付けられている全てのリグの名前を空白で区切って１つの文字列に結合し、この結合された文字列をself.rig_list（仮想属性）に設定する。
# -結果として、投稿に紐付いたリグが「リグ1 リグ2 リグ3」という形式の単一の文字列としてself.rig_listに保持されることになり、
#  フォーム等でユーザーがリグの編集を行う際にこの文字列を直接編集することで、リグの追加や削除を簡単に行うことができる。

# 82行目「before_update :update_rigs」
# -このコールバックは、Postモデルのレコードが更新される直前に実行されるコールバック。
# 実行時、フォームから送信された新しいリグのリスト（self.rig.list）を使用して、現在の投稿に紐つけられているリグ（rigs）の更新を行う。
# -更新とは、①新しいリグのリストに含まれているが、現在の投稿に紐つけていないリグは、新しく投稿に紐付ける。　②現在の投稿に紐付いているが、新しいリグリストに含まれていないリグは、投稿の紐付けから削除する。

# インスタンスとオブジェクトの違い
# オブジェクトは、データ（属性）とそれを操作するためのメソッド（関数）をカプセル化したもの
# インスタンスは、クラス（設計図）に基づいて作成されたオブジェクトの具体的な実体
# 差異：オブジェクトはプログラム上でデータと機能が一体となった構造のことを指し、インスタンスはそのオブジェクトが具体的にどのクラスから生成されたもの

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customer = Customer.find(params[:customer_id])
    @posts = Post.where(customer_id: params[:customer_id]).order(created_at: :desc).page(params[:page]).per(6)
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    post = Post.find(params[:id]).destroy
    redirect_to admin_customer_posts_path(post.customer)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_posts.html.erb
<% if @posts.any? %>
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-12 col-md-6 col-lg-4 mb-2">
        <div class="card mb-4 shadow">

          <!--カードヘッダー-->
          <%= link_to admin_customer_post_path(post.customer, post), class: "text-dark" do %>
          <div class="card-header mt-0 mb-0" style="background-color: white;">
            <div class="d-flex justify-content-between align-items-center">
              <div>
                <!--タイトル、10文字まで表示-->
                <h5><%= truncate(post.title, length: 10) %></h5>
                <!--魚の名前、10文字まで表示-->
                <% if post.genre_name.present? %>
                  <h6 class="mb-0" style="font-size: 1rem;">
                    <%= truncate(post.genre_name, length: 10) %>
                  </h6>
                <% end %>
              </div>

              <!-- 投稿日と釣り場 -->
              <div class="d-flex flex-column align-items-end">
                <div class="text-right" style="font-size: 0.9rem;">
                  <%= time_ago_in_words(post.created_at) %>前
                </div>
                <div class="text-right" style="font-size: 0.9rem;">
                  ＠<%= post.location %>
                </div>
              </div>
            </div>
          </div>

          <!--カードボディ-->
          <div class="card-body pb-0 pt-1" style="padding-left: 0.5rem;">
            <!-- 釣り方 -->
            <!--釣り方の有無の条件分岐-->
            <% if post.rigs.present? %>
              <p class="card-text" style="font-size: 0.9rem;">
                <% post.rigs.first(3).each do |rig| %>
                  <span style="color: #4d992f;">＃</span><%= rig.name %>
                <% end %>
                <!--釣り方の表示数の指定-->
                <% if post.rigs.count > 4 %>
                  <span>...</span>
                <% end %>
              </p>
            <% else %>
              <!-- rigsがない場合、同じサイズの余白を表示 -->
              <div style="min-height: 22px;"></div>
            <% end %>
          </div>
          
          <!--魚の画像-->
          <div class="my-3">
            <div class="my-3">
              <%= image_tag post.image.variant(resize_to_limit: [500, 250]).processed, class: "img-fluid", style: "width: 100%; height: 250px; object-fit: cover;" if post.image.attached? %>
              <%= image_tag 'no_image.jpg', class: "img-fluid", style: "width: 100%; height: 250px; object-fit: cover;" unless post.image.attached? %>
            </div>
          </div>
        <% end %>

          <!--管理者権限-->
          <div class="card-body pt-0 pb-0 mb-3 mx-auto">
            <%= link_to '管理者権限で削除', admin_customer_post_path(post.customer, post), method: :delete, data: { confirm: "本当に削除してもよろしいですか？" }, class: 'btn btn-danger btn-sm' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="text-center">投稿はありません</p>
<% end %>

app/views/admin/posts/index.html.erb
<div class="container mt-5">
 <!-- 管理者専用アラート -->
 <% if admin_signed_in? %>
    <div class="alert alert-warning" role="alert">
      <strong>注意：</strong> こちらは管理者専用画面です
    </div>
  <% end %>
  <!-- 投稿一覧セクション -->
  <div class="col-md-12">
    <h1 class="mb-4 text-center"><%= @customer.name %> さんの投稿一覧</h1>
    <%= render "admin/posts/posts", posts: @posts %>
  </div>
  <%= paginate @posts %>
</div>

app/views/admin/posts/show.html.erb
<div class="container mt-5">
  <!-- 管理者専用アラート -->
  <% if admin_signed_in? %>
    <div class="alert alert-warning" role="alert">
      <strong>注意：</strong> こちらは管理者専用画面です
    </div>
  <% end %>
  <div class="row">
    <!-- 投稿詳細 -->
    <div class="col-md-8 mx-auto">
      <div class="card">
        <!-- カードヘッダー -->
        <div class="card-header" style="background-color: white;">
          <!-- 投稿日とタイトル -->
          <div class="row align-items-center my-2">
            <div class="col text-left">
              <div class="d-flex align-items-center">
                <!-- タイトル -->
                <h4 class="mb-0"><%= truncate(@post.title, length: 20) %></h4>
              </div>
            </div>
            <div class="col text-right">
              <!-- 投稿日 -->
              <h6><%= l @post.created_at, format: :custom_long %></h6>
            </div>
          </div>

          <!-- 会員名 -->
          <div class="row align-items-center my-2">
            <div class="col">
              <h5><i class="fa-solid fa-user"></i> <%= link_to @post.customer.name, customer_path(@post.customer), class: "text-dark" %></h5>
            </div>
          </div>
        </div>

        <!-- カードボディ -->
        <div class="card-body">
          <!-- 釣り方 -->
          <!-- 釣り方の有無の条件分岐 -->
          <% if @post.rigs.present? %>
            <p class="card-text" style="font-size: 1.0rem;">
              <% @post.rigs.first(3).each do |rig| %>
                <span style="color: #4d992f;">＃</span><%= link_to rig.name, posts_path(rig_id: rig), class: "text-dark" %>
              <% end %>
              <!-- 釣り方の表示数の指定 -->
              <% if @post.rigs.count > 4 %>
                <span>...</span>
              <% end %>
            </p>
          <% else %>
            <!-- rigsがない場合、同じサイズの余白を表示 -->
            <div style="min-height: 22px;"></div>
          <% end %>
          <!-- 画像 -->
          <div class="my-3">
            <% if @post.image.attached? %>
              <%= image_tag @post.image, class: "img-fluid", style: "width: 100%; height: auto; object-fit: cover;" %>
            <% else %>
              <%= image_tag 'no_image.jpg', class: "img-fluid", style: "width: 100%; height: auto; object-fit: cover;" %>
            <% end %>
          </div>

          <!-- 魚と釣り場 -->
          <div class="row align-items-center my-2">
            <!-- 魚種 -->
            <div class="col">
              <h5>魚種</h5>
              <% if @post.genre_name.present? %>
                <h2 class="mb-0"><%= @post.genre_name %></h2>
              <% else %>
                <!-- もし魚が未記入で投稿が通ってしまった場合、このメッセージを表示して魚の登録を促す -->
                <%= link_to '魚種登録はこちらから', genres_path, class: 'text-dark' %>
              <% end %>
            </div>
            <!-- 釣り場 -->
            <div class="col">
              <h5>釣り場</h5>
              <h3 class="mb-0">＠ <%= link_to @post.location, posts_path(location: @post.location), class: "text-dark" %></h3>
            </div>
          </div>

          <!-- 感想 -->
          <div class="mb-3">
            <h5>感想</h5>
            <%= simple_format(@post.body, class: "m-0") %>
          </div>

          <hr>

          <!-- コメントとリプライ一覧 -->
          <h4>コメント件数 (<%= @post.post_comments.count %>)</h4>
          <div id="comments">
            <!-- コメントの有無の条件分岐 -->
            <% if @post.post_comments.where(parent_id: nil).order(created_at: :desc).exists? %>
              <% @post.post_comments.where(parent_id: nil).order(created_at: :desc).each do |comment| %>
                <div class="comment mb-3">
                  <!-- プロフィール画像 -->
                  <div class="d-flex align-items-center">
                    <% if comment.customer.image.attached? %>
                      <%= link_to customer_path(comment.customer) do %>
                        <%= image_tag comment.customer.image, class: "mr-2 rounded-circle", style: "height: 30px; width: 30px; object-fit: cover;" %>
                      <% end %>
                    <% else %>
                      <%= link_to customer_path(comment.customer) do %>
                        <%= image_tag 'no_image.jpg', class: "mr-2 rounded-circle", style: "height: 30px; width: 30px; object-fit: cover;" %>
                      <% end %>
                    <% end %>
                    <div>
                      <span><%= comment.customer.name %>さん</span>
                    </div>
                  </div>

                  <!-- コメント本文 -->
                  <div class="d-flex justify-content-between align-items-center mt-2" style="border: 1px solid #dee2e6; border-radius: 10px; background-color: #ffffff; padding: 15px;">
                    <span><%= simple_format(comment.comment, {}, wrapper_tag: "span") %></span>
                    <% if comment.customer == current_customer %>
                      <%= link_to '削除', post_post_comment_path(@post, comment), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-danger btn-sm" %>
                    <% end %>
                  </div>

                  <!-- コメント日時と返信 -->
                  <div class="d-flex justify-content-between align-items-center mt-2">
                    <p><%= link_to "返信", "#", class: "btn btn-primary btn-sm reply-link", data: { comment_id: comment.id } %></p>
                    <small><p class="text-muted"><i class="fas fa-calendar-alt mr-2" style="color: #e32d2d;"></i><%= l comment.created_at, format: :custom_long %></p></small>
                  </div>

                  <!-- リプライ一覧 -->
                  <!-- リプライの有無の条件分岐 -->
                  <% if comment.replies.order(created_at: :desc).exists? %>
                    <% comment.replies.order(created_at: :desc).each do |reply| %>
                      <div class="reply ml-4 pl-3 mt-2">
                        <div class="comment mb-3">
                          <!-- リプライの投稿者 -->
                          <div class="d-flex align-items-center">
                            <!-- プロフィール画像 -->
                            <% if reply.customer.image.attached? %>
                              <%= link_to customer_path(reply.customer) do %>
                                <%= image_tag reply.customer.image, class: "mr-2 rounded-circle", style: "height: 30px; width: 30px; object-fit: cover;" %>
                              <% end %>
                            <% else %>
                              <%= link_to customer_path(reply.customer) do %>
                                <%= image_tag 'no_image.jpg', class: "mr-2 rounded-circle", style: "height: 30px; width: 30px; object-fit: cover;" %>
                              <% end %>
                            <% end %>
                            <!-- 会員名 -->
                            <div>
                              <span><%= reply.customer.name %>さん</span>
                            </div>
                          </div>

                          <!-- リプライ本文 -->
                          <div class="d-flex justify-content-between align-items-center mt-2" style="border: 1px solid #dee2e6; border-radius: 10px; background-color: #ffffff; padding: 15px;">
                            <span><%= simple_format(reply.comment, {}, wrapper_tag: "span") %></span>
                            <% if reply.customer == current_customer %>
                              <%= link_to '削除', post_post_comment_path(@post, reply), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-danger btn-sm" %>
                            <% end %>
                          </div>

                          <!-- リプライ投稿日 -->
                          <div class="d-flex justify-content-end align-items-center mt-2">
                            <small><p class="text-muted"><i class="fas fa-calendar-alt mr-2" style="color: #e32d2d;"></i><%= l comment.created_at, format: :custom_long %></p></small>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  <% else %>
                    <p class="text-center">リプライはありません</p>
                  <% end %>
                </div>
              <% end %>
            <% else %>
              <p class="text-center">コメントはありません</p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- javascript/packs -->
<%= javascript_pack_tag 'reply' %>