config/routes.rb
Rails.application.routes.draw do
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in', as: :guest_customer_session
    get 'customers', to: 'public/registrations#new'
  end

  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admin/sessions#guest_sign_in', as: :guest_admin_session
  end

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    resources :customers, only: [:index] do
      member do
        patch :retire
        patch :revive
      end
      resources :posts, only: [:index, :show, :destroy] do
        resources :post_comments, only: [:index, :destroy]
      end
    end

    resources :genres, only: [:index, :destroy]

    resources :tackles, only: [:index, :show, :destroy]

    resources :post_comments, only: [:index, :destroy]
  end

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: 'public/registrations',
  sessions: 'public/sessions'
  }

  scope module: :public do
    root to: 'homes#top'
    get 'about', to: 'homes#about'

    get "customers/confirm" => "customers#confirm"
    patch "customers/withdraw" => "customers#withdraw"

    resources :customers, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :posts, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :edit, :destroy, :update]
      resource :favorites, only: [:create, :destroy]
      member do
       patch 'tackle_selection', to: 'posts#tackle_selection'
      end
    end

    resources :favorites, only: [:index]

    resources :notifications, only: [:index]

    resources :genres, only: [:index, :create, :edit, :update, :destroy] do
      get 'posts', to: 'posts#genre', as: 'posts', on: :member
    end

    resources :tackles, only: [:new, :create, :index, :show, :edit, :update, :destroy]
      get '/searches', to: 'searches#search'
      get 'tides/graf', to: 'tides#graf'
      get 'tides/get_port_name', to: 'tides#get_port_name'
    resources :tides, only: [:index]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anglers Spots</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/28e899c482.js" crossorigin="anonymous"></script>
    <!-- turbolinks有効にするときは下記の末尾に＝, 'data-turbolinks-track': 'reload' -->
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <!-- turbolinks有効にするときは下記の末尾に＝, 'data-turbolinks-track': 'reload' -->
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <header>
      <nav class="navbar-custom pt-2">
        <div class="container">
          <div class="row align-items-center justify-content-between">
          <!-- ロゴ -->
          <div class="col-auto">
            <%= link_to root_path, class: 'navbar-brand text-dark logo' do %>
              <span style="color: #fa870f;">Anglers</span><span style="color: #0e02e8;">Spots</span>
            <% end %>
          </div>
  
          <!-- リンク -->
          <div class="col-auto">
            <div class="navbar-links">
              <ul class="nav">
                <% if admin_signed_in? %>
                  <%= link_to '会員管理', admin_customers_path, class: 'btn btn-success btn-lg mr-3' %>
                  <%= link_to 'コメント管理', admin_post_comments_path, class: 'btn btn-success btn-lg mr-3' %>
                  <%= link_to '魚種管理', admin_genres_path, class: 'btn btn-warning btn-lg mr-3' %>
                  <%= link_to 'タックル管理', admin_tackles_path, class: 'btn btn-warning btn-lg mr-3' %>
                  <%= link_to '管理者ログアウト', destroy_admin_session_path, method: :delete, class: 'btn btn-primary btn-lg' %>
                <% elsif customer_signed_in? %>
                  <%= link_to '会員情報', customer_path(current_customer), class: 'nav-link' %>
                  <%= link_to '潮汐情報', tides_path, class: 'nav-link' %>
                  <%= link_to '投稿一覧', posts_path, class: 'nav-link' %>
                  <%= link_to '魚種一覧', genres_path, class: 'nav-link' %>
                  <%= link_to 'タックル一覧', tackles_path, class: 'nav-link' %>
                  <%= link_to 'いいね一覧', favorites_path, class: 'nav-link' %> 
                  <%= link_to '通知一覧', notifications_path, class: 'nav-link' %>
                  <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: 'nav-link' %>
                <% else %>
                  <%= link_to "ゲストログイン（閲覧用）", guest_customer_session_path, class: 'nav-link', method: :post %>
                  <%= link_to 'ログイン', new_customer_session_path, class: 'nav-link' %>
                  <%= link_to '新規登録', new_customer_registration_path, class: 'nav-link' %>
                <% end %>
              </ul>
            </div>
          </div>
          </div>
        </div>
      </nav>
    </header>

    <!-- メッセージ -->
    <% flash.each do |key, value| %>
    <div class="container mt-3">
      <div class="alert <%= 'alert-success' if key == 'notice' %> <%= 'alert-warning' if key == 'alert' %>" role="alert">
        <%= value %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
    <% end %>

    <%= yield %>

    <footer class="footer">
      <p>AnglersSpots</p>
    </footer>

    <!-- トップまで戻るボタン -->
    <button class="back-to-top btn btn-primary" style="position: fixed; bottom: 20px; right: 20px; display: none;">
    <i class="fas fa-arrow-up"></i>
    </button>

    <!-- BootstrapのJavaScript -->
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.3.1.slim.min.js' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js' %>

    <!-- CDN -->
    <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js' %>

    <!-- トップまで戻るボタン -->
    <%= javascript_pack_tag 'toggle_switch' %>
  </body>
</html>